import { ObjectId } from "mongodb";
import { Properties } from "./mongo";

export const properties: Properties[] = [
  {
    _id: new ObjectId("650000000000000000000001"),
    title: "One Bedroom Apartment in Skyview Tower",
    location: "Dubai Marina, Dubai | Apartment",
    priceAED: 1380000,
    investors: 0,
    status: "funded",
    annualisedReturn: "11.92%",
    currentValuationAED: 1380000,
    grossYield: "7.85%",
    netYield: "5.22%",
    investmentBreakdown: {
      propertyPrice: 1380000,
      purchaseCost: 118300,
      transactionCost: 26900,
      runningCost: 37200,
    },
    description: {
      details:
        "Skyview Tower in Dubai Marina offers luxurious waterfront living with modern layouts and breathtaking views of the skyline. Includes fitness facilities, swimming pools, and 24/7 concierge services. Prime location near Marina Walk and JBR ensures consistent rental demand and capital growth potential.",
      features: ["Fitness facilities", "Swimming pool", "Concierge services"],
    },
    features: {
      Bedroom: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/skyview-apt.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000002"),
    title: "Two Bedroom Apartment in Pearl Residences",
    location: "Jumeirah Village Circle, Dubai | Apartment",
    priceAED: 1050000,
    investors: 0,
    status: "open",
    annualisedReturn: "9.75%",
    currentValuationAED: 1050000,
    grossYield: "6.90%",
    netYield: "4.88%",
    investmentBreakdown: {
      propertyPrice: 1050000,
      purchaseCost: 92100,
      transactionCost: 24400,
      runningCost: 35100,
    },
    description: {
      details:
        "Pearl Residences in JVC offers spacious two-bedroom apartments with elegant interiors and community views. Residents enjoy landscaped gardens, fitness centers, and swimming pools with close proximity to main highways.",
      features: ["Landscaped gardens", "Fitness center", "Swimming pool"],
    },
    features: {
      Bedroom: 2,
      Bathroom: 2,
      Toilet: 2,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/pearl-residences.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000003"),
    title: "Studio Apartment in Marina Heights",
    location: "Dubai Marina, Dubai | Apartment",
    priceAED: 640000,
    investors: 0,
    status: "sold",
    annualisedReturn: "12.44%",
    currentValuationAED: 640000,
    grossYield: "8.10%",
    netYield: "5.44%",
    investmentBreakdown: {
      propertyPrice: 640000,
      purchaseCost: 58500,
      transactionCost: 16800,
      runningCost: 24300,
    },
    description: {
      details:
        "Marina Heights is a popular residential tower offering compact yet stylish studio apartments with easy access to Marina Mall, restaurants, and transport.",
      features: ["Close to Marina Mall", "Public transport access"],
    },
    features: {
      Studio: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
    },
    images: ["/images/marina-heights.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000004"),
    title: "One Bedroom Apartment in Creekside Views",
    location: "Dubai Creek Harbour, Dubai | Apartment",
    priceAED: 970000,
    investors: 0,
    status: "upcoming",
    annualisedReturn: "10.15%",
    currentValuationAED: 970000,
    grossYield: "7.20%",
    netYield: "4.95%",
    investmentBreakdown: {
      propertyPrice: 970000,
      purchaseCost: 89200,
      transactionCost: 21400,
      runningCost: 33200,
    },
    description: {
      details:
        "Creekside Views offers scenic living spaces with direct access to Dubai Creek Harbour. High-end finishes, a modern kitchen, and waterfront views. Near the upcoming Creek Tower development.",
      features: ["Waterfront views", "Modern kitchen"],
    },
    features: {
      Bedroom: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/creekside-views.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000005"),
    title: "Studio Apartment in Palm Jumeirah Residences",
    location: "Palm Jumeirah, Dubai | Apartment",
    priceAED: 715000,
    investors: 0,
    status: "funded",
    annualisedReturn: "14.20%",
    currentValuationAED: 715000,
    grossYield: "8.50%",
    netYield: "5.70%",
    investmentBreakdown: {
      propertyPrice: 715000,
      purchaseCost: 63900,
      transactionCost: 17500,
      runningCost: 25700,
    },
    description: {
      details:
        "Palm Jumeirah Residences are iconic beachfront properties offering studios with stunning sea views. Tenants enjoy private beach access, dining, and exclusive amenities.",
      features: ["Private beach access", "Sea views", "Exclusive amenities"],
    },
    features: {
      Studio: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
    },
    images: ["/images/palm-residences.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000006"),
    title: "One Bedroom Apartment in Horizon Tower",
    location: "Business Bay, Dubai | Apartment",
    priceAED: 1280000,
    investors: 0,
    status: "open",
    annualisedReturn: "13.05%",
    currentValuationAED: 1280000,
    grossYield: "8.20%",
    netYield: "5.40%",
    investmentBreakdown: {
      propertyPrice: 1280000,
      purchaseCost: 110900,
      transactionCost: 26200,
      runningCost: 36400,
    },
    description: {
      details:
        "Horizon Tower is in the heart of Business Bay near Downtown Dubai. Spacious layouts, premium finishes, and metro access ensure strong rental appeal.",
      features: ["Metro access", "Premium finishes"],
    },
    features: {
      Bedroom: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/horizon-tower.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000007"),
    title: "Two Bedroom Apartment in Lakeside Tower",
    location: "Jumeirah Lake Towers, Dubai | Apartment",
    priceAED: 1190000,
    investors: 0,
    status: "open",
    annualisedReturn: "9.85%",
    currentValuationAED: 1190000,
    grossYield: "7.00%",
    netYield: "4.78%",
    investmentBreakdown: {
      propertyPrice: 1190000,
      purchaseCost: 101300,
      transactionCost: 24100,
      runningCost: 34900,
    },
    description: {
      details:
        "Lakeside Tower offers spacious two-bedroom units with lake and skyline views. Popular among professionals due to connectivity and lifestyle amenities.",
      features: ["Lake views", "Skyline views", "Lifestyle amenities"],
    },
    features: {
      Bedroom: 2,
      Bathroom: 2,
      Toilet: 2,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/lakeside-tower.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000008"),
    title: "One Bedroom Apartment in Downtown Heights",
    location: "Downtown Dubai, Dubai | Apartment",
    priceAED: 1560000,
    investors: 0,
    status: "upcoming",
    annualisedReturn: "12.20%",
    currentValuationAED: 1560000,
    grossYield: "8.40%",
    netYield: "5.60%",
    investmentBreakdown: {
      propertyPrice: 1560000,
      purchaseCost: 134800,
      transactionCost: 28100,
      runningCost: 38800,
    },
    description: {
      details:
        "Downtown Heights provides premium apartments steps away from Burj Khalifa and Dubai Mall. Luxury finishes and spectacular city views ensure unmatched rental demand.",
      features: ["Near Burj Khalifa", "Luxury finishes", "City views"],
    },
    features: {
      Bedroom: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/downtown-heights.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000009"),
    title: "Studio Apartment in Green Oasis",
    location: "Al Furjan, Dubai | Apartment",
    priceAED: 585000,
    investors: 0,
    status: "sold",
    annualisedReturn: "11.50%",
    currentValuationAED: 585000,
    grossYield: "7.60%",
    netYield: "5.05%",
    investmentBreakdown: {
      propertyPrice: 585000,
      purchaseCost: 51200,
      transactionCost: 14900,
      runningCost: 23100,
    },
    description: {
      details:
        "Green Oasis offers affordable studio apartments in the growing Al Furjan community. New metro connectivity and highway access ensure rising rental demand.",
      features: ["Affordable units", "Metro connectivity"],
    },
    features: {
      Studio: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
    },
    images: ["/images/green-oasis.jpg"],
  },
  {
    _id: new ObjectId("650000000000000000000010"),
    title: "One Bedroom Apartment in Seaview Residences",
    location: "JBR, Dubai | Apartment",
    priceAED: 1420000,
    investors: 0,
    status: "funded",
    annualisedReturn: "13.60%",
    currentValuationAED: 1420000,
    grossYield: "8.60%",
    netYield: "5.75%",
    investmentBreakdown: {
      propertyPrice: 1420000,
      purchaseCost: 123600,
      transactionCost: 27100,
      runningCost: 37900,
    },
    description: {
      details:
        "Seaview Residences in JBR offers premium waterfront living with direct beach access. Fully furnished apartments with modern finishes are highly desirable for both short and long-term tenants.",
      features: ["Beach access", "Furnished apartments", "Modern finishes"],
    },
    features: {
      Bedroom: 1,
      Bathroom: 1,
      Toilet: 1,
      Kitchen: 1,
      Balcony: 1,
      Parking: 1,
      LivingRoom: 1,
    },
    images: ["/images/seaview-residences.jpg"],
  },
];
